//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogretmen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogretmen()
        {
            this.Soru = new HashSet<Soru>();
        }
    
        public int ogretmenID { get; set; }
        public int ogretmenDersID { get; set; }
        public int kullaniciID { get; set; }
    
        public virtual Ders Ders { get; set; }
        public virtual Kullanıcı Kullanıcı { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soru> Soru { get; set; }
    }
}
