//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogretmen
    {
        public int ogretmenID { get; set; }
        public string ogretmentDers { get; set; }
        public int kullaniciID { get; set; }
    
        public virtual Kullanıcı Kullanıcı { get; set; }
    }
}
