//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class sonCevaplar
    {
        public int id { get; set; }
        public string kn { get; set; }
        public Nullable<int> yanlisAdeti { get; set; }
    }
}
