//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soru
    {
        public int soruID { get; set; }
        public string soruMetin { get; set; }
        public string soruCevap { get; set; }
        public int soruDersID { get; set; }
        public int soruKonuID { get; set; }
        public string soruResim { get; set; }
        public int soruSeviye { get; set; }
        public int soruOgretmenID { get; set; }
        public string soruYanlisCevap { get; set; }
    
        public virtual Ders Ders { get; set; }
        public virtual Konu Konu { get; set; }
        public virtual Ogretmen Ogretmen { get; set; }
    }
}
